# This rule is not used by the project certs itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over in-cloud.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: certs
    app.kubernetes.io/managed-by: kustomize
  name: certificateset-admin-role
rules:
- apiGroups:
  - in-cloud.io
  resources:
  - certificatesets
  verbs:
  - '*'
- apiGroups:
  - in-cloud.io
  resources:
  - certificatesets/status
  verbs:
  - get
