apiVersion: in-cloud.io/v1alpha1
kind: CertificateSet
metadata:
  labels:
    app.kubernetes.io/name: certs
    app.kubernetes.io/managed-by: kustomize
  name: example-cluster
spec:
  environment: client
  issuerRef:
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    name: selfsigned-issuer
  kubeconfig: true
  kubeconfigEndpoint: "https://example-cluster.example.com:6443"
