name: release
on:
  push:
    branches:
      - "*"
      - feature/*
      - release/*
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

env:
  CHART_DIR: ./dist/chart
  REGISTRY: registry-1.docker.io
  OWNER: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: Create sanitized branch name
        id: sanitize
        run: echo "branch=$(echo ${GITHUB_REF_NAME} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Set chart version
        shell: bash
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          SANITIZE_BRANCH="${{ steps.sanitize.outputs.branch }}"
          SHORT_SHA="${{ steps.short-sha.outputs.sha }}"
          IMAGE_TAG="${SANITIZE_BRANCH}-${SHORT_SHA}"

          if [[ "$BRANCH" == release/* ]]; then
            NAME="${BRANCH#release/}"
            VERSION="${NAME}-${SHORT_SHA}"
          else
            VERSION="0.0.0-${IMAGE_TAG}"
          fi

          echo "Using chart version: $VERSION"
          yq -i ".version = \"${VERSION}\"" ${CHART_DIR}/Chart.yaml

          echo "UPD image tag: $IMAGE_TAG"
          yq -i ".manager.image.tag = \"${IMAGE_TAG}\"" ${CHART_DIR}/values.yaml

      - name: Package & Push
        run: |
          helm registry login registry-1.docker.io \
            -u prorobotech \
            -p ${{ secrets.DOCKERHUB_TOKEN }}

          pkg=$(helm package "${{ env.CHART_DIR }}" | awk '{print $NF}')
          helm push "$pkg" oci://registry-1.docker.io/prorobotech
